name: CI Pipeline

on:
  push:
    branches: [ main, feature/cicd ]
  pull_request:
    branches: [ main, feature/cicd ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # You can change this to your required version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install linting and testing tools
      run: |
        pip install flake8
        pip install pytest pytest-mock

    - name: Run linter
      run: |
        # Adjust the path to your source code if it's not root
        flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run unit tests
      run: |
        pytest tests/  # Make sure your test files are in the 'tests/' directory
